# Site settings
title: Cryptography Services
email: cryptoservices@nccgroup.com
description: > # this means to ignore newlines until "baseurl:"
  Cryptography Services is a dedicated team of consultants from NCC Group focused on cryptographic security assessments,
  protocol and design reviews, and tracking impactful developments in the space 
  of academia and industry.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://cryptoservices.github.io" # the base hostname & protocol for your site
twitter_username: NCCCrypto
github_username:  CryptoServices

# Build settings
markdown: kramdown
